# tasks/create_security_group.yml

- name: Create Security Group
  amazon.aws.ec2_group:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ region }}"
    state: present
    name: "{{ security_group_name }}"
    description: "Security group for SSH inbound and open outbound"
    tags:
      Name: "{{ security_group_name }}"
    rules:
      # Inbound rule: allow SSH (port 22) from any IP
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
        rule_desc: "Allow SSH inbound"

    rules_egress:
      # Outbound rule: allow all outbound traffic
      - proto: all
        cidr_ip: "0.0.0.0/0"
        rule_desc: "Allow all outbound traffic"
  register: security_group_results