# tasks/create_subnet.yml
- name: Create VPC Subnet
  amazon.aws.ec2_vpc_subnet:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ region }}"
    az: "{{ zone }}"
    state: present
    cidr: "{{ subnet_cidr_block }}"
    map_public: yes
    tags:
      Name: "{{ subnet_name }}"
  register: subnet_result